--- drivers/gpu/arm/mali/Kbuild
+++ drivers/gpu/arm/mali/Kbuild
@@ -98,12 +98,9 @@
 	linux/mali_pmu_power_up_down.o \
 	__malidrv_build_info.o
 
-ifneq ($(MALI_PLATFORM_FILES),)
-	mali-y += $(MALI_PLATFORM_FILES:.c=.o)
-endif
-
+#ifneq ($(MALI_PLATFORM_FILES),)
+mali-y += platform/pegasus-m400/mali_platform.o
 mali-$(CONFIG_MALI_DVFS) += platform/pegasus-m400/mali_platform_dvfs.o
-mali-$(CONFIG_MALI_DVFS) += platform/pegasus-m400/mali_platform.o
 
 mali-$(CONFIG_MALI400_PROFILING) += linux/mali_ukk_profiling.o
 mali-$(CONFIG_MALI400_PROFILING) += linux/mali_osk_profiling.o
